cluster.name: "go-demo-cluster"
node.name: "go-demo-node-1"
network.host: 0.0.0.0

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory settings
bootstrap.memory_lock: true

# Discovery settings for single node
discovery.type: single-node

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring settings (deprecated in ES 8.x, use Metricbeat instead)
# xpack.monitoring.collection.enabled: true  # This setting is deprecated in ES 8.x

# Index settings for log data
action.auto_create_index: "+go-demo-*,+kibana*,+.monitoring-*,+.watches,+.triggered_watches,+.watcher-history-*,+.ml-*"

# Performance tuning
indices.memory.index_buffer_size: 10%
indices.memory.min_index_buffer_size: 48mb

# Index lifecycle management (enabled by default in ES 8.x, no longer configurable)
# xpack.ilm.enabled: true  # This setting is deprecated and removed in ES 8.x

# Index settings will be handled via index templates, not node config
# See monitoring/elasticsearch/templates/go-demo-logs-template.json